const images = {
  authImg: require('../assets/images/auth-bg.jpg'),
  authMidCircle: require('../assets/images/auth-midCircle.png'),
  radiusAuth: require('../assets/images/radiusAuth.png'),
  arrowLeft: require('../assets/images/arrow-left.png'),
  logo: require('../assets/images/logo.png'),
  male: require('../assets/images/male_avatar.svg'),
  female: require('../assets/images/female_avatar.svg'),
  SocialIcons: require('../assets/images/ChatsCircle.png'),
  ConnectIcons: require('../assets/images/Heart.png'),
  marketIcon: require('../assets/images/ShoppingBag.png'),
  gymIcon: require('../assets/images/Barbell.png'),
  MoreIcons: require('../assets/images/List.png'),
  notifcationIcon: require('../assets/images/PaperPlaneTilt.png'),
  Share: require('../assets/images/share.png'),
  comment: require('../assets/images/comment.png'),
  downloadIcon: require('../assets/images/DownloadSimple.png'),
  menuIcon: require('../assets/images/menu.png'),
  CreatePlus: require('../assets/images/Plus.png'),
  CreateVideo: require('../assets/images/VideoCamera.png'),
  EditIcon: require('../assets/icons/post/PencilSimpleLine.png'),
  BoostIcon: require('../assets/icons/post/AlignBottom.png'),
  DeleteIcon: require('../assets/icons/post/TrashSimple.png'),
  reportIcons: require('../assets/icons/post/Warning.png'),
  eysIcon: require('../assets/icons/post/EyeSlash.png'),
  followIcon: require('../assets/icons/post/UserPlus.png'),
  bellIcon: require('../assets/icons/Bell.png'),
  transactions: require('../assets/icons/more/Receipt.png'),
  topUp : require('../assets/icons/more/PaperPlane.png'),
  withdraw : require('../assets/icons/more/Vector.png'),
};

export default images;
