import { Notification } from './types';

export const mockNotifications: Notification[] = [
  {
    id: '1',
    title: 'Gym Services Available',
    message: 'Get the best services on gym paddy anytime, meet new people, buy and sell and build your body with in the gym section',
    date: '01/01/25',
    timestamp: '04:22 AM',
    isRead: false,
    type: 'promotion',
  },
  {
    id: '2',
    title: 'Gym Services Available',
    message: 'Get the best services on gym paddy anytime, meet new people, buy and sell and build your body with in the gym section',
    date: '01/01/25',
    timestamp: '04:22 AM',
    isRead: true,
    type: 'promotion',
  },
  {
    id: '3',
    title: 'Gym Services Available',
    message: 'Get the best services on gym paddy anytime, meet new people, buy and sell and build your body with in the gym section',
    date: '01/01/25',
    timestamp: '04:22 AM',
    isRead: true,
    type: 'promotion',
  },
  {
    id: '4',
    title: 'Gym Services Available',
    message: 'Get the best services on gym paddy anytime, meet new people, buy and sell and build your body with in the gym section',
    date: '01/01/25',
    timestamp: '04:22 AM',
    isRead: true,
    type: 'promotion',
  },
  {
    id: '5',
    title: 'Gym Services Available',
    message: 'Get the best services on gym paddy anytime, meet new people, buy and sell and build your body with in the gym section',
    date: '01/01/25',
    timestamp: '04:22 AM',
    isRead: false,
    type: 'promotion',
  },
  {
    id: '6',
    title: 'Gym Services Available',
    message: 'Get the best services on gym paddy anytime, meet new people, buy and sell and build your body with in the gym section',
    date: '01/01/25',
    timestamp: '04:22 AM',
    isRead: false,
    type: 'promotion',
  },
  {
    id: '7',
    title: 'Gym Services Available',
    message: 'Get the best services on gym paddy anytime, meet new people, buy and sell and build your body with in the gym section',
    date: '01/01/25',
    timestamp: '04:22 AM',
    isRead: false,
    type: 'promotion',
  },
];