import { Transaction, Gift } from './types';

export const mockTransactions: Transaction[] = [
  {
    id: '1',
    type: 'withdrawal',
    amount: 2500,
    date: '01/01/25',
    timestamp: '07:22 AM',
  },
  {
    id: '2',
    type: 'deposit',
    amount: 2500,
    date: '01/01/25',
    timestamp: '07:22 AM',
  },
  {
    id: '3',
    type: 'withdrawal',
    amount: 2500,
    date: '01/01/25',
    timestamp: '07:22 AM',
  },
  {
    id: '4',
    type: 'deposit',
    amount: 2500,
    date: '01/01/25',
    timestamp: '07:22 AM',
  },
  {
    id: '5',
    type: 'withdrawal',
    amount: 2500,
    date: '01/01/25',
    timestamp: '07:22 AM',
  },
  {
    id: '6',
    type: 'deposit',
    amount: 2500,
    date: '01/01/25',
    timestamp: '07:22 AM',
  },
  {
    id: '7',
    type: 'deposit',
    amount: 2500,
    date: '01/01/25',
    timestamp: '07:22 AM',
  },
];

export const mockGifts: Gift[] = [
  {
    id: '1',
    type: 'sent',
    amount: 250500,
    description: 'You sent a lion to Adewale',
    recipient: 'Adewale',
    date: '01/01/25',
    timestamp: '07:22 AM',
  },
  {
    id: '2',
    type: 'sent',
    amount: 2500,
    description: 'You sent GP tokens to Anita',
    recipient: 'Anita',
    date: '01/01/25',
    timestamp: '07:22 AM',
  },
  {
    id: '3',
    type: 'sent',
    amount: 2500,
    description: 'You sent a bear to sammy',
    recipient: 'sammy',
    date: '01/01/25',
    timestamp: '07:22 AM',
  },
  {
    id: '4',
    type: 'received',
    amount: 2500,
    description: 'You received a lion from Adewale',
    sender: 'Adewale',
    date: '01/01/25',
    timestamp: '07:22 AM',
  },
  {
    id: '5',
    type: 'sent',
    amount: 2500,
    description: 'You sent a bear to sammy',
    recipient: 'sammy',
    date: '01/01/25',
    timestamp: '07:22 AM',
  },
  {
    id: '6',
    type: 'received',
    amount: 2500,
    description: 'You received a lion from Adewale',
    sender: 'Adewale',
    date: '01/01/25',
    timestamp: '07:22 AM',
  },
  {
    id: '7',
    type: 'received',
    amount: 2500,
    description: 'You received a lion from Adewale',
    sender: 'Adewale',
    date: '01/01/25',
    timestamp: '07:22 AM',
  },
];